name: Mopidy
version: 1.0.4
slug: mopidy
panel_icon: mdi:music-circle
description: Mopidy Music Server
url: https://github.com/bram96/Hassio-Addons/tree/main/mopidy
ingress: true
ingress_port: 6680
ingress_entry: iris/
arch:
  - armv7
  - armhf
  - amd64
  - i386
homeassistant: 0.115.0
startup: system
init: false
audio: true
devices:
  - /dev/snd
map:
  - share:rw
  - media:rw
ports:
  6680/tcp: 6680
  6600/tcp: 6600
ports_description:
  6680/tcp: Web Frontend
  6600/tcp: MDP Connection
options:
  media_folder: /media/mopidy/media
  playlist_folder: /media/mopidy/playlists
  locale: en_US
  country: en
  audio_output: audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! tcpclientsink host=local-snapcast-server port=4955
schema:
  media_folder: match(/share/.+|/media/.+|(smb|nfs)://.+)
  playlist_folder: match(/share/.+|/media/.+|(smb|nfs)://.+)
  custom_config: match(/share/mopidy/.+)?
  locale: match([a-z]{2}_[A-Z{2}])
  country: match([a-z]{2})
  audio_output: match(.*)
