name: Snapcast Server
version: 1.0.3
slug: snapcast-server
panel_icon: mdi:music-circle
description: Snapcast Server
url: https://github.com/bram96/Hassio-Addons/tree/main/snapcast-server
audio: true
host_network: true
ingress: true
ingress_port: 1780
arch:
  - armv7
  - armhf
  - amd64
  - i386
homeassistant: 0.115.0
startup: system
init: false
audio: true
devices:
  - /dev/snd
map:
  - share:rw
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  4954/tcp: 4954
ports_description:
  1704/tcp: Snapcast client connections
  1705/tcp: Snapcast's control interface
  1780/tcp: Snapcast websocket connections and web-interface
options:
  streams:
    streams: []
  buffer: 1000
  codec: flac
  send_to_muted: false
  sampleformat: "48000:16:2"
  spotify_name: "Home Assistant Sound System"
  log_level: info
schema:
  # Use nested option to force yaml editor on addon's config page
  streams:
    streams: ["str"]
  buffer: int
  codec: list(pcm|flac|vorbis|opus)
  send_to_muted: bool
  sampleformat: str
  spotify_name: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
